name: Test

on:
  workflow_dispatch: # Allow to manually trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: quadrum-solutions/mercury
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: Generate metadata file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "dir/fileName.txt"
        FILE_DATA: ${{DOCKER_METADATA_OUTPUT_JSON}}

    - name: Test output
      run: cat dir/fileName.txt