name: Test

on:
  workflow_dispatch: # Allow to manually trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate metadata file
      uses: hashicorp/actions-generate-metadata@main
      id: execute
      with:
        repository: consul-terraform-sync
        version: make version
        metadataFileName: metadata.json