name: Test

on:
  workflow_dispatch: # Allow to manually trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate metadata file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "dir/fileName.txt"
        FILE_DATA: "file content"