name: Test

on:
  workflow_dispatch: # Allow to manually trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: name/app

    - name: Generate metadata file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "dir/fileName.txt"
        FILE_DATA: "file content"
    - name: Test output
      run: cat dir/fileName.txt