name: Test

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']
  workflow_dispatch: # Allow to manually trigger

env:
  DOCKER_FILE: ./Dockerfile.prod
  DOCKER_FILE_K8: ./DockerfileK8.prod
  REGISTRY_GH: ghcr.io
  REGISTRY_DH: docker.io
  IMAGE_NAME_GH: ${{ github.repository }}
  IMAGE_NAME_DH: quadrumsolution/freddie
  IMAGE_NAME_DH_K8: quadrumsolution/freddiek8
  HASH_FILE_NAME: /tmp/freddie/${{ github.ref_name }}.txt

jobs:
  tag:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.9.0
        with:
          images: |
            ${{ env.REGISTRY_DH }}/${{ env.IMAGE_NAME_DH_K8 }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}


      - name: Echo
        run: |
          echo determine_latest : ${{ needs.determine_latest.outputs.on_main }}
          echo meta : ${{ steps.meta.outputs.tags }}

